/**
 * Google Form Auto-Filler — Constants & Message Protocol
 * Defines all action types, state machine statuses, and timeouts.
 */

export const MSG = {
  // UI -> Content Script
  GET_FORM_SCHEMA: "GFAF_GET_FORM_SCHEMA",
  FILL_CURRENT_FORM: "GFAF_FILL_CURRENT_FORM", // Quick Test mode (no submit)

  // Content Script -> UI / Background
  FORM_SCHEMA_RESPONSE: "GFAF_FORM_SCHEMA_RESPONSE",
  FILL_COMPLETED: "GFAF_FILL_COMPLETED",
  SUBMISSION_STARTED: "GFAF_SUBMISSION_STARTED",
  CONFIRMATION_DETECTED: "GFAF_CONFIRMATION_DETECTED",
  FRESH_FORM_READY: "GFAF_FRESH_FORM_READY",
  AUTOMATION_ERROR: "GFAF_AUTOMATION_ERROR",

  // UI -> Background
  START_BULK_RUN: "GFAF_START_BULK_RUN",
  STOP_BULK_RUN: "GFAF_STOP_BULK_RUN",
  PAUSE_BULK_RUN: "GFAF_PAUSE_BULK_RUN",
  RESUME_BULK_RUN: "GFAF_RESUME_BULK_RUN",
  GET_RUN_STATE: "GFAF_GET_RUN_STATE",

  // Background -> Content Script
  EXECUTE_FILL_AND_SUBMIT: "GFAF_EXECUTE_FILL_AND_SUBMIT",
  NAVIGATE_FRESH_FORM: "GFAF_NAVIGATE_FRESH_FORM"
};

export const RUN_STATUS = {
  IDLE: "IDLE",
  FILLING: "FILLING",
  SUBMITTING: "SUBMITTING",
  WAITING_FOR_CONFIRMATION: "WAITING_FOR_CONFIRMATION",
  WAITING_DELAY: "WAITING_DELAY",
  OPENING_FRESH_FORM: "OPENING_FRESH_FORM",
  PAUSED: "PAUSED",
  STOPPED: "STOPPED",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR"
};

export const QUESTION_TYPES = {
  RADIO: "radio",
  CHECKBOX: "checkbox",
  DROPDOWN: "dropdown",
  SCALE: "scale",
  TEXT: "text",
  PARAGRAPH: "paragraph",
  DATE: "date",
  UNSUPPORTED: "unsupported"
};

export const TEXT_STRATEGIES = {
  FIXED: "fixed",
  POOL: "pool",
  SKIP_IF_OPTIONAL: "skip_if_optional",
  STOP_IF_REQUIRED: "stop_if_required"
};

export const TIMEOUTS = {
  WAIT_FOR_FORM_MS: 15000,
  WAIT_FOR_SUBMIT_MS: 10000,
  WAIT_FOR_CONFIRMATION_MS: 20000,
  WAIT_FOR_FRESH_FORM_MS: 20000
};

export const STORAGE_KEYS = {
  RUN_STATE: "gfaf_run_state",
  FORM_CONFIGS: "gfaf_form_configs",
  LOGS: "gfaf_debug_logs"
};
